version: "3.8"

networks:
  togo-test:

services:
  togo-test:
    build:
      context: .
      dockerfile: test.dockerfile
    volumes:
      - $PWD:/go/src/togo
    environment:
      - HOST=db
      - PORT=5432
      - USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
    depends_on:
      - db
    networks:
      - togo-test

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - dbdata_postgres:/var/lib/postgresql/data
    networks:
      - togo-test

volumes:
  dbdata_postgres:
